Repository SPADUG/POSHTools, pull requests merged in 2021-10, with the labels that each got.

#3 New Optimize-VHDXProfile function
  .gitignore
  CHANGELOG.md
  POSHTools/Classes/classA.ps1
  POSHTools/POSHTools.psd1
  POSHTools/POSHTools.psm1
  POSHTools/Private/GetHelloWorld.ps1
  POSHTools/Public/Clear-VHDXProfile.ps1
  POSHTools/Public/Convert-User2SID.ps1
  build.ps1
  psakeFile.ps1
  requirements.psd1
  tests/Help.tests.ps1
  tests/Manifest.tests.ps1
  tests/Meta.tests.ps1
  tests/MetaFixers.psm1
  tests/ScriptAnalyzerSettings.psd1
  tests/out/testResults.xml
Labels: hacktoberest-accepted

#4 add function to approve WSUS
  POSHTools/Public/Approve-WSUSUpdate.ps1
  requirements.psd1
Labels: enhancement, hacktoberest-accepted

#7 ADD FUNCTION EDL VM
  POSHTools/Public/Get-EDLVm.ps1
Labels: enhancement, good first issue, hacktoberest-accepted

#9 Add function to clear content from VHDX file
  POSHTools/Public/Optimize-VHDXProfile.ps1
Labels: enhancement, Hacktoberfest, hacktoberest-accepted

#12 Add function to find a user on RDS server
  POSHTools/Public/Find-UserOnRds.ps1
  POSHTools/Public/Get-RdsServerList.ps1
  docs/en-EN/Approve-WSUSUpdate.md
  docs/en-EN/Clear-VHDXProfile.md
  docs/en-EN/Convert-User2SID.md
  docs/en-EN/Find-UserOnRDS.md
  docs/en-EN/Get-EDLVm.md
  docs/en-EN/Get-RdsServerList.md
  docs/en-EN/Optimize-VHDXProfile.md
  docs/en-EN/Test-FileIsLocked.md
Labels: enhancement, Hacktoberfest, hacktoberest-accepted
